service: lighthouse-on-lambda
description: 'Record lighthouse score on spreadsheets'

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'ap-northeast-1'}
  environment:
    TARGET_URL: 'https://howdy39.dev'
    WEBHOOK_URL: 'https://script.google.com/macros/s/AKfycbyMw1wxBBGqYolnrTFTwGIx63DKBQSS-ZKvscZuJTgtthmN1CcI/exec'

functions:
  auditor:
    handler: handler.audit
    # layers:
      # - arn:aws:lambda:ap-northeast-1:244165946632:layer:test:1 #250MB超えでエラー
      # - ${cf:lighthouse-on-lambda-prod.TestLambdaLayerQualifiedArn} #250MB超えでエラー`
    description: 'Chromeを動かすのでそれなりにメモリが必要'
    memorySize: 768
    timeout: 120
    events:
      - schedule:
          rate: cron(0 9 * * ? *)
          enabled: true

layers:
  lighthouse:
    path: ./layer
    description: Layer with all the required dependencies to run google lighthouse
    compatibleRuntimes:
      - nodejs10.x
    licenseInfo: MIT
    retain: true
