service: lighthouse-function
description: 'Record lighthouse score on spreadsheets'

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'ap-northeast-1'}
  environment:
    TARGET_URL: 'https://howdy39.dev'
    WEBHOOK_URL: 'https://script.google.com/macros/s/AKfycbyMw1wxBBGqYolnrTFTwGIx63DKBQSS-ZKvscZuJTgtthmN1CcI/exec'

functions:
  auditor:
    handler: index.handler
    layers:
      - ${cf:lighthouse-layer-${self:provider.stage}.LighthouseLambdaLayerQualifiedArn}
    description: 'Chromeを動かすのでそれなりにメモリが必要'
    memorySize: 768
    timeout: 120
    events:
      - schedule:
          rate: cron(0 9 * * ? *)
          enabled: true
